spring:
  security:
    oauth2:
      client:
        registration:
          piggymetrics:
            client-id: account-service
            client-secret: ${ACCOUNT_SERVICE_PASSWORD}
            authorization-grant-type: client_credentials
            scope: server
        provider:
          piggymetrics:
            token-uri: http://auth-service:5000/uaa/oauth/token

  data:
    mongodb:
      host: account-mongodb # Kubernetes Service Name
      database: piggymetrics
      username: user
      password: ${MONGODB_PASSWORD}
      port: 27017      
